version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: alenev-site:latest
    container_name: alenev-site
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.example.description=Anton Lenev personal website"
      - "com.example.version=1.0.0"
