version: '3.8'

services:
  dev:
    image: oven/bun:1
    container_name: alenev-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: sh -c "bun install && bun run dev --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
